$modelname player/john/hl2mp_anims.mdl

$include "..\Humans\male\commonbones.qci"
$include "..\Humans\standardhierarchy.qci"
$include "..\Humans\standardikchains.qci"
$include "..\Humans\male\hitbox.qci"

//$lockbonelengths

//$lockdefinebones

$include "player_macros.qci"

$include "player_anims.qci"

$attachment "eyes" "ValveBiped.Bip01_Head1" 0 -4 67.5 absolute
//$include "body_poses_lean.qci"
